import { Button } from "@/components/ui/button";
import { Lock, Pencil, Sparkles } from "lucide-react";
import type { CellCounts } from "./phase-logic";
import { ImprovementProposalsPanel } from "./ImprovementProposalsPanel";

interface PhaseDecideProps {
  taskId: string;
  versionTag: string | null;
  cells: CellCounts;
  /** Patient IDs available for improvement runs. */
  patientIds: string[];
  /** Navigate the workspace to the DRAFT phase so the methodologist can edit criteria. */
  onRevise: () => void;
  /** Trigger the lock transition — caller handles the API call + maturity state update. */
  onLock: () => void;
  /** True when every cell is fresh (stale === 0 and validated === total). Lock is only
   *  enabled when this is true. */
  canLock: boolean;
  /** Run the chart-review-improve skill against the validated annotations.
   *  Caller resolves the cohort + handles the long-running agent call. */
  onImprove?: () => void;
  /** True while the improvement run is in flight. */
  isImproving?: boolean;
  /** Number of proposals generated by the most recent improvement run. */
  improveProposalCount?: number;
  /** Bumped when the improvement run finishes so the proposals panel
   *  re-fetches without manual refresh. */
  improveRefreshKey?: number;
}

/**
 * DECIDE phase — shows validation summary and exposes two equally-weighted CTAs:
 * "Revise" (back to DRAFT with a new version) and "Lock" (advance to LOCK phase).
 * The Lock button is disabled when any cell is stale or unvalidated.
 *
 * Also exposes an "Improve" button that triggers the improve skill and streams
 * its stdout into a log panel below.
 */
export function PhaseDecide({
  taskId,
  versionTag,
  cells,
  patientIds,
  onRevise,
  onLock,
  canLock,
  onImprove,
  isImproving,
  improveProposalCount,
  improveRefreshKey,
}: PhaseDecideProps) {
  const staleCount = cells.stale;
  const unvalidated = cells.total - cells.validated;

  return (
    <div className="mx-auto max-w-[640px] space-y-8 py-8">
      {/* Summary */}
      <div>
        <div className="text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
          Validation summary{versionTag ? ` · ${versionTag}` : ""}
        </div>
        <h2
          className="mt-2 font-display text-[28px] tracking-tight"
          style={{ fontVariationSettings: '"opsz" 28, "SOFT" 50' }}
        >
          {cells.validated} of {cells.total} cells validated
        </h2>
        {staleCount > 0 && (
          <p className="mt-2 text-[13px] text-[hsl(var(--ochre))]">
            {staleCount} stale {staleCount === 1 ? "cell" : "cells"} — criteria changed since last validation.
          </p>
        )}
        {unvalidated > 0 && staleCount === 0 && (
          <p className="mt-2 text-[13px] text-muted-foreground">
            {unvalidated} {unvalidated === 1 ? "cell" : "cells"} not yet validated.
          </p>
        )}
        {canLock && (
          <p className="mt-2 text-[13px] text-[hsl(var(--sage))]">
            All cells are fresh and validated. Ready to lock.
          </p>
        )}
      </div>

      {/* Lock gate explanation */}
      {!canLock && (
        <div className="rounded-md border border-[hsl(var(--ochre))]/30 bg-[hsl(var(--ochre))]/5 px-4 py-3 text-[12.5px] text-[hsl(var(--ochre))]">
          <strong>Lock requires every cell to be fresh.</strong> Resolve stale cells or
          finish validation before locking. Alternatively, revise the rubric to start
          a new version.
        </div>
      )}

      {/* Improve — a third option that uses the validated annotations
       *  + override comments to propose criterion-level guideline edits.
       *  Sits between Revise and Lock conceptually: "look at what humans
       *  disagreed with, propose tightening for the next iter." */}
      {onImprove && (
        <div className="rounded-md border border-[hsl(var(--ochre))]/30 bg-[hsl(var(--ochre))]/5 px-4 py-3 space-y-2">
          <div className="flex items-start gap-2">
            <Sparkles size={14} className="text-[hsl(var(--ochre))] mt-0.5 shrink-0" />
            <div className="flex-1 text-[12.5px] space-y-1">
              <strong className="text-[hsl(var(--ochre))]">Improve the guideline.</strong>{" "}
              <span className="text-muted-foreground">
                The chart-review-improve skill reads your validated annotations and
                clusters disagreement signal into concrete criterion-level edits.
              </span>
              <details className="text-[11.5px] text-muted-foreground/90 mt-1">
                <summary className="cursor-pointer hover:text-foreground">
                  What signals does it use?
                </summary>
                <ul className="list-disc pl-4 mt-1 space-y-0.5">
                  <li>
                    <strong>Reviewer overrides</strong> — fields where you changed an
                    agent's draft answer.
                  </li>
                  <li>
                    <strong>Comments</strong> — anything you typed in the optional
                    "Comment · used to refine guideline" field on a criterion.
                  </li>
                  <li>
                    <strong>Reviewer-vs-agent answer divergence</strong> — your
                    submitted answer differs from every agent's draft answer on the
                    same criterion (compared via files in <code>runs/</code> vs
                    <code> reviews/</code>).
                  </li>
                  <li>
                    <strong>Rationale departures</strong> — your written rationale
                    diverges from the agent's reasoning across multiple patients.
                  </li>
                </ul>
                <p className="mt-1">
                  If your validation was mostly "Copy from Agent" + Submit (no edits,
                  no comments), the skill has nothing to cluster and will report zero
                  proposals — that's correct, not a bug.
                </p>
              </details>
              <p className="text-[11.5px] text-muted-foreground">
                Output: rule proposals at <code>proposals/&lt;guideline-id&gt;/*.yaml</code> →
                visible in <strong>Lock → Drain rule queue</strong>.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-3 pt-1">
            <Button
              variant="outline"
              size="sm"
              onClick={onImprove}
              disabled={isImproving}
              className="gap-1.5"
            >
              <Sparkles size={12} />
              {isImproving ? "Running improvement… (~30s-2m)" : "Run improvement"}
            </Button>
            {improveProposalCount != null && improveProposalCount > 0 && (
              <span className="text-[11.5px] text-[hsl(var(--sage))]">
                ✓ {improveProposalCount} proposal{improveProposalCount === 1 ? "" : "s"} written.
                Review them in <strong>Lock → Drain rule queue</strong>.
              </span>
            )}
            {improveProposalCount === 0 && (
              <span className="text-[11.5px] text-muted-foreground">
                ✓ Run complete — 0 new proposals. Either your validations match the
                agents (no signal to cluster) or no patterns crossed the cluster
                threshold. Add reviewer comments or override agent answers to
                generate signal.
              </span>
            )}
          </div>
        </div>
      )}

      {/* Iterate vs exit — explicit framing. The two iteration paths
       *  (Improve + Revise) belong to the cycle the reviewer is currently
       *  in; Lock is the exit ramp out of the cycle. Splitting them into
       *  two visually-distinct rows makes the "you're going around again"
       *  vs "you're done iterating" decision obvious. */}
      <div className="space-y-4">
        <div>
          <div className="text-[10px] uppercase tracking-[0.18em] text-muted-foreground mb-2">
            This iteration — keep going around the cycle?
          </div>
          <div className="rounded-md border border-border bg-card/40 px-4 py-3 text-[12.5px] text-muted-foreground">
            <strong className="text-foreground">Improve</strong> generates rule proposals
            from this iteration's data (above).{" "}
            <strong className="text-foreground">Revise</strong> takes you back to{" "}
            <strong>Author</strong> to apply edits and start the next iteration —
            agents re-run, you re-validate, then come back here.
          </div>
          <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">
            <Button
              variant="outline"
              size="lg"
              className="h-16 flex-col gap-1"
              onClick={onRevise}
            >
              <Pencil size={16} />
              <span>Revise → next iteration</span>
              <span className="text-[10px] font-normal text-muted-foreground">
                edit guideline, re-run agents, re-validate
              </span>
            </Button>
          </div>
        </div>

        <div className="border-t border-border/60 pt-4">
          <div className="text-[10px] uppercase tracking-[0.18em] text-muted-foreground mb-2">
            Exit the cycle — freeze this version
          </div>
          <Button
            variant="default"
            size="lg"
            className="h-16 w-full flex-col gap-1"
            disabled={!canLock}
            onClick={onLock}
          >
            <Lock size={16} />
            <span>Lock</span>
            <span className="text-[10px] font-normal opacity-70">
              one-way · no further edits accepted on this version
            </span>
          </Button>
        </div>
      </div>

      {/* Improvement proposals — runs + error banner (A4) + analysis summary (A5) */}
      <ImprovementProposalsPanel taskId={taskId} patientIds={patientIds} />
    </div>
  );
}
