import { Button } from "@/components/ui/button";
import { Lock, Pencil, Sparkles } from "lucide-react";
import type { CellCounts } from "./phase-logic";
import { ImprovementProposalsPanel } from "./ImprovementProposalsPanel";
import { PackagesPanel } from "./PackagesPanel";

interface PhaseDecideProps {
  taskId: string;
  iterId?: string;
  versionTag: string | null;
  cells: CellCounts;
  /** Patient IDs available for improvement runs. */
  patientIds: string[];
  /** Navigate the workspace to the DRAFT phase so the methodologist can edit criteria. */
  onRevise: () => void;
  /** Trigger the lock transition — caller handles the API call + maturity state update. */
  onLock: () => void;
  /** True when every cell is fresh (stale === 0 and validated === total). Lock is only
   *  enabled when this is true. */
  canLock: boolean;
  /** Kept for API compatibility with Workspace caller — phenotype only now. */
  taskKind?: "phenotype";
  /** Run the chart-review-improve skill against the validated annotations. */
  onImprove?: () => void;
  /** True while the improvement run is in flight. */
  isImproving?: boolean;
  /** Number of proposals generated by the most recent improvement run. */
  improveProposalCount?: number;
  /** Bumped when the improvement run finishes so the proposals panel re-fetches. */
  improveRefreshKey?: number;
  onRunAgain?: () => void;
  isRunningAgain?: boolean;
  /** Active session id for the packages panel. */
  activeSessionId?: string | null;
}

/**
 * DECIDE phase — shows validation summary and exposes two equally-weighted CTAs:
 * "Revise" (back to DRAFT with a new version) and "Lock" (advance to LOCK phase).
 * The Lock button is disabled when any cell is stale or unvalidated.
 */
export function PhaseDecide({
  taskId,
  iterId: _iterId,
  versionTag,
  cells,
  patientIds,
  onRevise,
  onLock,
  canLock,
  onImprove,
  isImproving,
  improveProposalCount,
  improveRefreshKey,
  onRunAgain: _onRunAgain,
  isRunningAgain: _isRunningAgain,
  activeSessionId,
}: PhaseDecideProps) {
  const staleCount = cells.stale;
  const unvalidated = cells.total - cells.validated;

  return (
    <div className="mx-auto max-w-[640px] space-y-8 py-8">
      {/* Summary */}
      <div>
        <div className="text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
          Validation summary{versionTag ? ` · ${versionTag}` : ""}
        </div>
        <h2
          className="mt-2 font-display text-[28px] tracking-tight"
          style={{ fontVariationSettings: '"opsz" 28, "SOFT" 50' }}
        >
          {cells.validated} of {cells.total} cells validated
        </h2>
        {staleCount > 0 && (
          <p className="mt-2 text-[13px] text-[hsl(var(--ochre))]">
            {staleCount} stale {staleCount === 1 ? "cell" : "cells"} — criteria changed since last validation.
          </p>
        )}
        {unvalidated > 0 && staleCount === 0 && (
          <p className="mt-2 text-[13px] text-muted-foreground">
            {unvalidated} {unvalidated === 1 ? "cell" : "cells"} not yet validated.
          </p>
        )}
        {canLock && (
          <p className="mt-2 text-[13px] text-[hsl(var(--sage))]">
            All cells are fresh and validated. Ready to lock.
          </p>
        )}
      </div>

      {/* Lock gate explanation */}
      {!canLock && (
        <div className="rounded-md border border-[hsl(var(--ochre))]/30 bg-[hsl(var(--ochre))]/5 px-4 py-3 text-[12.5px] text-[hsl(var(--ochre))]">
          <strong>Lock requires every cell to be fresh.</strong> Resolve stale cells or
          finish validation before locking. Alternatively, revise the rubric to start a new version.
        </div>
      )}

      {/* Suggestions panel */}
      {onImprove && (
        <div className="space-y-3">
          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="sm"
              onClick={onImprove}
              disabled={isImproving}
              className="gap-1.5"
            >
              <Sparkles size={12} />
              {isImproving ? "Looking for improvements… (~30s-2m)" : "Look for improvements"}
            </Button>
            <span className="text-[11.5px] text-muted-foreground">
              Reads your validated annotations and proposes criterion-level edits.
            </span>
          </div>
          <ImprovementProposalsPanel
            taskId={taskId}
            patientIds={patientIds}
            refreshKey={improveRefreshKey}
          />
          {improveProposalCount === 0 && (
            <div className="text-[11.5px] text-muted-foreground">
              ✓ Run complete — no new suggestions. Either your validation matches
              the agents or no patterns crossed the cluster threshold.
            </div>
          )}
        </div>
      )}

      {/* Packages — snapshot the rubric for reuse. */}
      {activeSessionId && (
        <div className="border-t border-border/60 pt-6">
          <PackagesPanel taskId={taskId} activeSessionId={activeSessionId} />
        </div>
      )}

      {/* Bottom action row: Revise + Lock side by side. */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 pt-2">
        <Button
          variant="outline"
          size="lg"
          className="h-16 flex-col gap-1"
          onClick={onRevise}
        >
          <Pencil size={16} />
          <span>Revise → next iteration</span>
          <span className="text-[10px] font-normal text-muted-foreground">
            edit guideline, re-run agents, re-validate
          </span>
        </Button>
        <Button
          variant="default"
          size="lg"
          className="h-16 flex-col gap-1"
          disabled={!canLock}
          onClick={onLock}
        >
          <Lock size={16} />
          <span>Lock</span>
          <span className="text-[10px] font-normal opacity-70">
            one-way · no further edits accepted
          </span>
        </Button>
      </div>
    </div>
  );
}
