import { Button } from "@/components/ui/button";
import { Lock, Pencil, Sparkles } from "lucide-react";
import type { CellCounts } from "./phase-logic";
import { ImprovementProposalsPanel } from "./ImprovementProposalsPanel";
import { AdherenceDecideSummary } from "./AdherenceDecideSummary";
import { NerCalibrationFigure } from "./NerCalibrationFigure";
import { PackagesPanel } from "./PackagesPanel";

interface PhaseDecideProps {
  taskId: string;
  /** Active iter id — required for adherence's per-agent IAA fetch.
   *  Phenotype/NER don't currently need it. */
  iterId?: string;
  versionTag: string | null;
  cells: CellCounts;
  /** Patient IDs available for improvement runs. */
  patientIds: string[];
  /** Navigate the workspace to the DRAFT phase so the methodologist can edit criteria. */
  onRevise: () => void;
  /** Trigger the lock transition — caller handles the API call + maturity state update. */
  onLock: () => void;
  /** True when every cell is fresh (stale === 0 and validated === total). Lock is only
   *  enabled when this is true. */
  canLock: boolean;
  /** Active task_kind. NER tasks render "spans" / "notes" terminology;
   *  adherence renders "questions"; phenotype renders "cells". */
  taskKind?: "phenotype" | "ner" | "adherence";
  /** Run the chart-review-improve skill against the validated annotations.
   *  Caller resolves the cohort + handles the long-running agent call. */
  onImprove?: () => void;
  /** True while the improvement run is in flight. */
  isImproving?: boolean;
  /** Number of proposals generated by the most recent improvement run. */
  improveProposalCount?: number;
  /** Bumped when the improvement run finishes so the proposals panel
   *  re-fetches without manual refresh. */
  improveRefreshKey?: number;
  /** Start a new iter on the SAME cohort with the (now-updated) skill.
   *  Used by adherence's "Run again" loop: reviewer's persisted answers
   *  carry over as the gold standard, so iter 2+ scores automatically
   *  without re-validation. */
  onRunAgain?: () => void;
  /** True while a new iter is being started. */
  isRunningAgain?: boolean;
  /** Active session id for the packages panel — packages are tagged
   *  with their source session, so this lets the user generate a
   *  snapshot of "what this session's rubric looks like right now." */
  activeSessionId?: string | null;
}

/**
 * DECIDE phase — shows validation summary and exposes two equally-weighted CTAs:
 * "Revise" (back to DRAFT with a new version) and "Lock" (advance to LOCK phase).
 * The Lock button is disabled when any cell is stale or unvalidated.
 *
 * Also exposes an "Improve" button that triggers the improve skill and streams
 * its stdout into a log panel below.
 */
export function PhaseDecide({
  taskId,
  iterId,
  versionTag,
  cells,
  patientIds,
  onRevise,
  onLock,
  canLock,
  onImprove,
  isImproving,
  improveProposalCount,
  improveRefreshKey,
  onRunAgain,
  isRunningAgain,
  activeSessionId,
  taskKind,
}: PhaseDecideProps) {
  const staleCount = cells.stale;
  const unvalidated = cells.total - cells.validated;
  const unit = taskKind === "ner" ? "note" : taskKind === "adherence" ? "question" : "cell";
  const unitPl = taskKind === "ner" ? "notes" : taskKind === "adherence" ? "questions" : "cells";

  return (
    <div className="mx-auto max-w-[640px] space-y-8 py-8">
      {/* Summary */}
      <div>
        <div className="text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
          Validation summary{versionTag ? ` · ${versionTag}` : ""}
        </div>
        <h2
          className="mt-2 font-display text-[28px] tracking-tight"
          style={{ fontVariationSettings: '"opsz" 28, "SOFT" 50' }}
        >
          {cells.validated} of {cells.total} {unitPl} validated
        </h2>
        {staleCount > 0 && (
          <p className="mt-2 text-[13px] text-[hsl(var(--ochre))]">
            {staleCount} stale {staleCount === 1 ? unit : unitPl}
            {taskKind === "ner"
              ? " — ontology or guidance changed since last validation."
              : " — criteria changed since last validation."}
          </p>
        )}
        {unvalidated > 0 && staleCount === 0 && (
          <p className="mt-2 text-[13px] text-muted-foreground">
            {unvalidated} {unvalidated === 1 ? unit : unitPl} not yet validated.
          </p>
        )}
        {canLock && (
          <p className="mt-2 text-[13px] text-[hsl(var(--sage))]">
            All {unitPl} are fresh and validated. Ready to lock.
          </p>
        )}
      </div>

      {/* Lock gate explanation */}
      {!canLock && (
        <div className="rounded-md border border-[hsl(var(--ochre))]/30 bg-[hsl(var(--ochre))]/5 px-4 py-3 text-[12.5px] text-[hsl(var(--ochre))]">
          <strong>Lock requires every {unit} to be fresh.</strong> Resolve stale {unitPl} or
          finish validation before locking. Alternatively, revise the
          {taskKind === "ner" ? " annotation guidance" : taskKind === "adherence" ? " question framework + rules" : " rubric"} to start a new version.
        </div>
      )}

      {/* Adherence — per-agent leaderboard against reviewer's persisted
       *  answers. The score panel replaces the bare counter above as the
       *  primary signal for whether the skill is ready to lock. */}
      {taskKind === "adherence" && iterId && (
        <AdherenceDecideSummary taskId={taskId} iterId={iterId} />
      )}

      {/* NER — per-agent precision / recall / F1 + tuple-κ against the
       *  reviewer-validated spans. Reuses the same NerCalibrationFigure
       *  component the LOCK page renders so the scores on DECIDE and
       *  LOCK match exactly (sophisticated tuple+IoU matching, not just
       *  exact-span_id). The figure is task-scoped, not iter-scoped —
       *  the cumulative validated review_state is the single source
       *  of truth. */}
      {taskKind === "ner" && (
        <NerCalibrationFigure taskId={taskId} />
      )}

      {/* Suggestions panel — one compact Improve trigger above; the
       *  ImprovementProposalsPanel below renders proposal cards (plain
       *  English + Accept/Dismiss). Collapsed from the old 3-section
       *  layout into one block since the cards explain themselves. */}
      {onImprove && (
        <div className="space-y-3">
          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="sm"
              onClick={onImprove}
              disabled={isImproving}
              className="gap-1.5"
            >
              <Sparkles size={12} />
              {isImproving ? "Looking for improvements… (~30s-2m)" : "Look for improvements"}
            </Button>
            <span className="text-[11.5px] text-muted-foreground">
              {taskKind === "ner"
                ? "Diffs the agent drafts against your validated spans and suggests edits to the annotation guidance."
                : taskKind === "adherence"
                  ? "Diffs the agent's QuestionAnswers against your adjudicated verdicts and proposes question / rule edits."
                  : "Reads your validated annotations and proposes criterion-level edits."}
            </span>
          </div>
          <ImprovementProposalsPanel
            taskId={taskId}
            patientIds={patientIds}
            refreshKey={improveRefreshKey}
          />
          {improveProposalCount === 0 && (
            <div className="text-[11.5px] text-muted-foreground">
              ✓ Run complete — no new suggestions. Either your validation matches
              the agents or no patterns crossed the cluster threshold.
            </div>
          )}
        </div>
      )}

      {/* "Run again" CTA — re-runs the agents on the SAME cohort with
       *  whatever's currently in the skill bundle. The reviewer's
       *  validated state (adherence: persisted answers; NER: validated
       *  span_labels) carries over as the gold standard, so the next
       *  iter's score is computed automatically. This is the inner
       *  loop: improve skill (or accept proposals) → run again → see
       *  the new score on the LOCK/DECIDE calibration panel. */}
      {(taskKind === "adherence" || taskKind === "ner") && onRunAgain && (
        <div className="pt-2">
          <Button
            variant="default"
            size="lg"
            className="h-16 w-full flex-col gap-1"
            onClick={onRunAgain}
            disabled={isRunningAgain}
          >
            <Sparkles size={16} />
            <span>{isRunningAgain ? "Starting a new iter…" : "Run agents again on this cohort"}</span>
            <span className="text-[10px] font-normal opacity-80">
              {taskKind === "ner"
                ? "uses the current entity_type_guidance · validated spans carry over"
                : "uses the current questions / rules · reviewer answers carry over"}
            </span>
          </Button>
        </div>
      )}

      {/* Packages — snapshot the rubric for reuse. Only meaningful with
       *  an active session, since each package records its source. */}
      {activeSessionId && (
        <div className="border-t border-border/60 pt-6">
          <PackagesPanel taskId={taskId} activeSessionId={activeSessionId} />
        </div>
      )}

      {/* Bottom action row: Revise + Lock side by side. Lock is gated by
       *  canLock; the warning banner above already explains why. */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 pt-2">
        <Button
          variant="outline"
          size="lg"
          className="h-16 flex-col gap-1"
          onClick={onRevise}
        >
          <Pencil size={16} />
          <span>Revise → next iteration</span>
          <span className="text-[10px] font-normal text-muted-foreground">
            {taskKind === "ner"
              ? "edit annotation guidance, re-run agents, re-validate"
              : taskKind === "adherence"
                ? "edit questions / rules, re-run agents, re-adjudicate"
                : "edit guideline, re-run agents, re-validate"}
          </span>
        </Button>
        <Button
          variant="default"
          size="lg"
          className="h-16 flex-col gap-1"
          disabled={!canLock}
          onClick={onLock}
        >
          <Lock size={16} />
          <span>Lock</span>
          <span className="text-[10px] font-normal opacity-70">
            one-way · no further edits accepted
          </span>
        </Button>
      </div>
    </div>
  );
}
